# Generated by Django 3.2.8 on 2022-04-10 03:07

import API.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('C', 'Cliente'), ('E', 'Empresa')], default='C', editable=False, max_length=1)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('apellido', models.CharField(max_length=255, null=True)),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters')], verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('C', 'Cliente'), ('E', 'Empresa')], default='E', editable=False, max_length=1)),
                ('nombre', models.CharField(max_length=255, null=True, verbose_name='Nombre o Razon social')),
                ('ruc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters')])),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('property_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to=API.utils.get_input_image_path, verbose_name='Path de imagen de entrada')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSegmentation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre')),
                ('front_input_image', models.FileField(blank=True, null=True, upload_to=API.utils.get_output_image_path, verbose_name='Imagen fontal')),
                ('side_input_image', models.FileField(blank=True, null=True, upload_to=API.utils.get_output_image_path, verbose_name='Imagen de perfil')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=255, null=True, verbose_name='Nombre de sede')),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('ciudad', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='API.empresa')),
            ],
            options={
                'db_table': 'local',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('neck', models.FloatField(default=0)),
                ('chest', models.FloatField(default=0)),
                ('waist', models.FloatField(default=0)),
                ('hip', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('arm', models.FloatField(default=0)),
                ('leg', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creado en')),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('img_url', models.TextField()),
            ],
            options={
                'db_table': 'tela',
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.cliente')),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=255, null=True)),
                ('ciudad', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'contacto_cliente',
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('inventario', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('empresas', models.ManyToManyField(related_name='prendas', to='API.Empresa')),
                ('tela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telas', to='API.tela')),
            ],
            options={
                'db_table': 'prenda',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pedido', models.CharField(choices=[('P', 'Pendinte'), ('C', 'Confirmado'), ('F', 'Fallido')], default='P', max_length=1)),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de entrega')),
                ('placed_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cliente', to='API.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_empresa', to='API.empresa')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_local', to='API.local')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medidas_pedido', to='API.measurement')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='API.pedido')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prendas_pedido', to='API.prenda')),
            ],
            options={
                'db_table': 'itemPedido',
            },
        ),
    ]
