# Generated by Django 3.2.8 on 2022-05-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='empresas',
            field=models.ManyToManyField(db_table='prenda_empresa', related_name='prendas', to='API.Empresa'),
        ),
    ]
