# Generated by Django 3.2.8 on 2022-04-21 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tela',
            old_name='url_iamgen',
            new_name='url_imagen',
        ),
    ]
