# Generated by Django 3.2.8 on 2022-04-10 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_delete_contactocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=255, null=True)),
                ('ciudad', models.CharField(max_length=255, null=True)),
                ('cliente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.cliente')),
            ],
            options={
                'db_table': 'contacto_cliente',
            },
        ),
    ]
