# Generated by Django 3.2.8 on 2022-05-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_prenda_empresas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tela',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tela',
            name='url_imagen',
            field=models.URLField(verbose_name='url_imagen'),
        ),
    ]
