# Generated by Django 3.2.8 on 2022-04-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_url_iamgen_tela_url_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenda',
            old_name='precio',
            new_name='precio_sugerido',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='inventario',
        ),
    ]
