# Generated by Django 3.2.8 on 2022-04-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_contactocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactocliente',
            name='cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacto', to='API.cliente'),
        ),
    ]
