# Generated by Django 3.2.8 on 2022-05-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20220515_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
    ]
