# Generated by Django 3.2.8 on 2022-05-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_prenda_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='url_imagen',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='url_imagen'),
        ),
    ]
