# Generated by Django 3.2.8 on 2022-04-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_contactocliente_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_medida', to='API.measurement'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='prenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_prenda', to='API.prenda'),
        ),
    ]
