# Generated by Django 3.2.8 on 2022-04-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_prenda_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='tela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telas', to='API.tela'),
        ),
    ]
