# Generated by Django 3.2.8 on 2022-04-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_prenda_tela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_medida', to='API.measurement'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='API.pedido'),
        ),
    ]
