# Generated by Django 3.2.8 on 2022-04-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20220410_0938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'prenda', 'medida')},
        ),
    ]
