# Generated by Django 3.2.8 on 2022-04-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_itempedido_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Confirmado'), ('F', 'Fallido')], default='P', max_length=1),
        ),
    ]
