# Generated by Django 3.2.8 on 2022-04-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='local',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locales', to='API.empresa'),
        ),
    ]
