# Generated by Django 3.2.8 on 2022-04-14 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20220410_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='tela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prendas', to='API.tela'),
        ),
    ]
