# Generated by Django 3.2.8 on 2022-04-16 05:19

import API.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_alter_prenda_tela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesegmentation',
            name='front_input_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=API.utils.get_output_image_path, verbose_name='Imagen fontal'),
        ),
        migrations.AlterField(
            model_name='imagesegmentation',
            name='side_input_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=API.utils.get_output_image_path, verbose_name='Imagen de perfil'),
        ),
    ]
